name: Change Repository Visibility
description: Issue to request a change in repository visibility
title: "[Change Repository Visibility]: organization_name/repository_name"
labels: [":pencil2: request",":white_check_mark: todo"]
assignees:
  - mouismail
body:
  - type: markdown
    attributes:
      value: |
        **View the [governance guide](#) for this request**
        
  - type: checkboxes
    id: current_visibility
    attributes:
      label: What's the repository current visibility?
      options:
        - label: 'Private'
        - label: 'Internal'
        - label: 'Public'
    validations:
        required: true

  - type: checkboxes
    id: new_visibility
    attributes:
      label: What's the repository new visibility?
      options:
        - label: 'Private'
        - label: 'Internal'
        - label: 'Public'
    validations:
        required: true
  - type: input
    id: repo
    attributes:
      label: What is the repository's name?
      placeholder: Respoitory Name
    validations:
        required: true     
  - type: input
    id: org
    attributes:
      label: What is the organization's name?
      placeholder: Organization Name
    validations:
        required: true
  - type: textarea
    id: justification
    attributes:
      label: What is the justification for this change?
      placeholder: justification
    validations:
        required: true
