# Learn more about the syntax here:
# https://docs.github.com/en/early-access/github/save-time-with-slash-commands/syntax-for-user-defined-slash-commands
---
trigger: approve
title: review change request
# Works everywhere by default. Uncomment to limit it to certain surfaces.
surfaces:
  - issue
#   - pull_request
#   - discussions
description: Form to request a change in repository visibility

# Each command has one or more steps. You can add up to 25 steps.
steps:
  # This displays a menu, similar to typing `@`.
  - type: menu
    id: visibility
    label: Options
    options:
      - Private
      - Internal
      - Public
  # This displays a form with a dropdown, text input, and markdown editor.
  - type: form
    style: modal
    body:
      - type: dropdown
        id: status
        attributes:
          label: Priority
          options:
          - label: "🟢 Approve"
          - label: "🔴 Rejected"
          - label: "🟡 Requsted for more details"
      - type: textarea
        id: justification
        attributes:
          label: Justification
          placeholder: justification for changing the repository visibility
  - type: fill
    template: |-
      Requested has been reviewed by @mouismail and the request has been {{ data.status }} 
      ### Justification
      {{ data.justification }}
