# Learn more about the syntax here:
# https://docs.github.com/en/early-access/github/save-time-with-slash-commands/syntax-for-user-defined-slash-commands
---
trigger: approve
title: review change request
# Works everywhere by default. Uncomment to limit it to certain surfaces.
surfaces:
  - issue
#   - pull_request
#   - discussions
description: Form to request a change in repository visibility

# Each command has one or more steps. You can add up to 25 steps.
steps:
  # This displays a menu, similar to typing `@`.
  - type: menu
    id: visibility
    label: visibility
    options:
      - Private
      - Internal
      - Public
  # This displays a form with a dropdown, text input, and markdown editor.
  - type: form
    style: modal
    body:
      - type: dropdown
        attributes:
          label: status
          options:
          - label: "🟢 Approved"
          - label: "🔴 Rejected"
          - label: "🟡 Requsted for more details"
      - type: textarea
        attributes:
          label: Justification
          placeholder: justification for changing the repository visibility
  - type: fill
    template: |-
      The request to change the repository visibility has been reviewed as following:
      - **Request visibility**: {{ data.visibility }}
      - **Status**: {{ data.status }}
      - **Justification**: {{ data.Justification }}
