# Learn more about the syntax here:
# https://docs.github.com/en/early-access/github/save-time-with-slash-commands/syntax-for-user-defined-slash-commands
---
trigger: repo_visibility
title: Change Repository Visibility
# Works everywhere by default. Uncomment to limit it to certain surfaces.
surfaces:
  - issue
#   - pull_request
#   - discussions
description: Form to request a change in repository visibility

# Each command has one or more steps. You can add up to 25 steps.
steps:
  # This displays a menu, similar to typing `@`.
  - type: menu
    id: visibility
    label: Options
    options:
      - Private
      - Internal
      - Public
  # This displays a form with a dropdown, text input, and markdown editor.
  - type: form
    style: modal
    body:
      - type: dropdown
        id: priority
        attributes:
          label: Priority
          options:
          - label: "🟢 Normal"
          - label: "⚠️ Important"
          - label: "💥 Emergency"
      - type: input
        id: org
        attributes:
          label: org
          format: text
      - type: input
        id: repo
        attributes:
          label: repo
          format: text
      - type: textarea
        id: justification
        attributes:
          label: Justification
          placeholder: justification for changing the repository visibility
  - type: fill
    template: |-
      Thank you for creating request to change {{org}}/{{repo}} to {{visibility}}.
      Here is the data you provided:

      ### Oragnization: {{org}}
      ### Repository: {{repo}}
      ### Visibility: {{visibility}}
      ### Priority: {{priority}}
      ### Justification: {{justification}}

      We will review your request and get back to you as soon as possible.
