name: Shared Volume Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    services:
      my-service:
        image: busybox
        entrypoint: sh
        command: -c "chown -R nobody:nobody /data && echo 'Hello' > /data/file1.txt && echo 'World' > /data/file2.txt"
        volumes:
          - my-volume:/data
    steps:
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: /data

  job2:
    runs-on: ubuntu-latest
    needs: job1
    services:
      my-service:
        image: busybox
        entrypoint: sh
        command: -c "chown -R nobody:nobody /data && cat /data/file1.txt && cat /data/file2.txt"
        volumes:
          - my-volume:/data
    steps:
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: /data-download

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Print downloaded files
        run: |
          cat /data-download/file1.txt
          cat /data-download/file2.txt
