name: Shared Volume Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    services:
      my-service:
        image: busybox
        volumes:
          - my-volume:/data
    steps:
      - name: Create files
        run: |
          echo 'Hello' > /data/file1.txt
          echo 'World' > /data/file2.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    services:
      my-service:
        image: busybox
        volumes:
          - my-volume:/data
    steps:
      - name: Use files
        run: |
          cat /data/file1.txt
          cat /data/file2.txt
