name: Shared Volume Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create volume
        run: docker volume create my-volume
      - name: Store files to volume
        run: |
          docker run --rm -v my-volume:/data busybox sh -c "echo 'Hello' > /data/file1.txt && echo 'World' > /data/file2.txt"
    services:
      my-service:
        image: busybox
        volumes:
          - my-volume:/data

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Download files from service volume
        run: |
          docker run --rm -v my-volume:/data busybox sh -c "cp /data/file1.txt /github/workspace && cp /data/file2.txt /github/workspace"
      - name: Use files
        run: |
          cat file1.txt
          cat file2.txt
